every 1 seconds:
	loop all players:
		if {scboard.%loop-player%} is true:
			wipe loop-player's sidebar
			set name of sidebar of loop-player to "scoreboard test"
			set score "닉네임 : %loop-player%" in sidebar of loop-player to 3
			set score "asdf2" in sidebar of loop-player to 2
			set score "asdf2" in sidebar of loop-player to 1
			set score "asdf2" in sidebar of loop-player to -1
			set score "asdf2" in sidebar of loop-player to -2